// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/1/2026, 10:13:16 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/lpatel/Code/LP-DEV/Awesome-Skills/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/lpatel/Code/LP-DEV/Awesome-Skills/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/lpatel/Code/LP-DEV/Awesome-Skills/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/lpatel/Code/LP-DEV/Awesome-Skills/plugins/**/*.{js,ts,mjs}","/home/lpatel/Code/LP-DEV/Awesome-Skills/composables/**/*.{js,ts,mjs}","/home/lpatel/Code/LP-DEV/Awesome-Skills/utils/**/*.{js,ts,mjs}","/home/lpatel/Code/LP-DEV/Awesome-Skills/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/lpatel/Code/LP-DEV/Awesome-Skills/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/lpatel/Code/LP-DEV/Awesome-Skills/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/lpatel/Code/LP-DEV/Awesome-Skills/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;